-- SkuMenu — menu contribution registry + layout map, root assembly, and central
-- sibling-list helpers. Workstream 2 (menu rework) of the Sku 42 rework.
--
-- PHASE A — additive plumbing that makes the ROOT menu assembly data-driven
-- WITHOUT changing the rendered tree. Today the top level is a hardcoded inline
-- sequence in SkuZOptions/Core.lua: one `InjectMenuItems(... ) + dynamic +
-- BuildChildren -> Module:MenuBuilder` block per module. Here that becomes:
--   * a REGISTRY of module "contributions" (id -> {label, build}) — WHAT a
--     module puts on the menu and how it builds its subtree, and
--   * a LAYOUT list (`rootLayout`) — WHERE/in-what-order those ids appear at the
--     root. Re-ordering the root is then a data edit to `rootLayout`, with no
--     code change and no hand-maintained sibling chain (the contribution/layout
--     decoupling that is the headline win of W2).
--
-- This sits ON TOP OF the existing rendering layer (SkuGenericMenuItem template +
-- SkuOptions:InjectMenuItems) — it is behaviour-preserving, not a renderer
-- replacement. The toggle/enum/range settings nodes are still generated by the
-- existing `SkuOptions:IterateOptionsArgs`.
--
-- CANONICAL MENU-CONSTRUCTION STYLE (W6-B #9, closing the old "later phase M-B"):
-- there are two layers and they are BOTH intentional, not a half-finished
-- migration —
--   * BuildNode/Build (below) is the composition SHELL: use it for structural
--     nodes (kind = list / submenu / action / settings) whose shape is
--     data-describable.
--   * SkuOptions:IterateOptionsArgs is the canonical LEAF renderer for the
--     toggle/enum/range/select settings nodes (driven by the SkuSettings schema).
-- The imperative SkuOptions:InjectMenuItems remains the primitive both sit on and
-- is fine for bespoke/dynamic subtrees. Do NOT mass-convert the existing
-- InjectMenuItems call sites to declarative specs — that re-expresses the same
-- calls for no gain; reach for BuildNode/Build only when authoring new structure.
--
-- Lives on ns.Menu with a global SkuMenu alias (mirrors SkuUtil / SkuSettings).
--
-- Load position: TOC-loaded EARLY (right after SkuSettings.lua), before the
-- feature modules and before SkuZOptions/Core.lua. Only function definitions and
-- the registry population run at load; the renderer (InjectMenuItems) and the
-- module builders are resolved lazily, at menu-open time, when AssembleRoot runs.

local ADDON_NAME, ns = ...
ns = ns or {}

ns.Menu = ns.Menu or {}
SkuMenu = ns.Menu

-- registry[id] = { label = <string | function -> string>, build = function(entry),
--                  sorting = <bool?> }. `build` receives the dynamic root
-- entry as its argument and populates its children (same contract the old inline
-- BuildChildren closures had: build the subtree under the passed entry).
SkuMenu.registry = SkuMenu.registry or {}

-- Ordered list of registered ids shown at the root, top to bottom. THIS is the
-- layout — editing the order reorders the root menu with no code change. The
-- Accessibility ("Menue 7") grouping is still appended inline by
-- SkuZOptions/Core.lua after this list (a special hand-built grouping slated to
-- fold into the registry/layout in a later step).
SkuMenu.rootLayout = SkuMenu.rootLayout or {}

---------------------------------------------------------------------------------------------------------------------------------------
-- Register a module's root contribution.
function SkuMenu:RegisterModule(aId, aSpec)
	if type(aId) ~= "string" or type(aSpec) ~= "table" then
		if dprint then dprint("SkuMenu:RegisterModule: bad args", tostring(aId)) end
		return self
	end
	self.registry[aId] = aSpec
	return self
end

-- Set/replace the root layout order (a list of registered ids).
function SkuMenu:SetRootLayout(aIdList)
	self.rootLayout = aIdList or {}
	return self
end

---------------------------------------------------------------------------------------------------------------------------------------
-- Resolve a spec's label (string or function) at assembly time. Falls back to
-- the id so a mis-registered label never produces a nil menu name.
local function resolveLabel(aSpec, aId)
	local lbl = aSpec.label
	if type(lbl) == "function" then
		local ok, r = pcall(lbl)
		if ok and r ~= nil then return r end
		return aId
	end
	if lbl ~= nil then return lbl end
	return aId
end

-- Inject one registered module as a dynamic root entry whose BuildChildren runs
-- the registered builder. Mirrors EXACTLY the old hand-written per-module block
-- (entry.dynamic = true; BuildChildren -> Module:MenuBuilder(entry)). Returns the
-- created entry (or nil for an unregistered id).
function SkuMenu:InjectModuleEntry(aRootMenu, aId)
	local spec = self.registry[aId]
	if not spec then
		if dprint then dprint("SkuMenu:InjectModuleEntry: unregistered id", tostring(aId)) end
		return nil
	end
	local tEntry = SkuOptions:InjectMenuItems(aRootMenu, {resolveLabel(spec, aId)}, SkuGenericMenuItem)
	tEntry.id = aId  -- stable nav anchor = the registry id (W6-B #14): every root
	                 -- menu is now reachable by a locale-independent id, not its
	                 -- localized display label.
	tEntry.dynamic = true
	if spec.sorting then
		tEntry.sorting = true
	end
	local buildFn = spec.build
	tEntry.BuildChildren = function(self)
		if buildFn then
			buildFn(self)
		end
	end
	return tEntry
end

-- Assemble the registered root entries, in layout order, into aRootMenu.
-- Injecting one at a time into the same parent reproduces the original prev/next
-- sibling chain exactly (InjectMenuItems links each new item to the previous).
function SkuMenu:AssembleRoot(aRootMenu)
	for i = 1, #self.rootLayout do
		self:InjectModuleEntry(aRootMenu, self.rootLayout[i])
	end
	return self
end

---------------------------------------------------------------------------------------------------------------------------------------
-- Central sibling-list helpers. Insertion already routes through InjectMenuItems
-- (which wires prev/next centrally); REMOVAL is the asymmetric gap today — ad-hoc
-- sites re-derive position by index and can leave the prev/next chain broken.
-- These give one splice point for both, for the M-D phase to route removals
-- through (not yet wired into existing callers — additive for now).

-- Append items under a parent via the existing renderer. Returns the last entry.
function SkuMenu:Insert(aParent, aNames, aTemplate)
	return SkuOptions:InjectMenuItems(aParent, aNames, aTemplate or SkuGenericMenuItem)
end

-- Remove an entry from its parent's children, fixing the prev/next sibling chain.
-- Handles both parent shapes the renderer uses: a node (list in parent.children)
-- and the root array (the parent IS the list). Returns the removed entry.
function SkuMenu:Remove(aEntry)
	if not aEntry or not aEntry.parent then
		return aEntry
	end
	local siblings = aEntry.parent.children or aEntry.parent
	local idx
	for x = 1, #siblings do
		if siblings[x] == aEntry then
			idx = x
			break
		end
	end
	if not idx then
		return aEntry
	end
	local prev, nxt = aEntry.prev, aEntry.next
	if prev then prev.next = nxt end
	if nxt then nxt.prev = prev end
	table.remove(siblings, idx)
	aEntry.prev, aEntry.next = nil, nil
	return aEntry
end

---------------------------------------------------------------------------------------------------------------------------------------
-- Declarative node compiler (W2 Phase B, M-B). Translates a flat list of node
-- SPECS into template nodes via the existing renderer, so a MenuBuilder can be
-- expressed as DATA instead of repeated hand-written InjectMenuItems blocks.
-- This is the composition layer only — SETTINGS-backed nodes (toggle/enum/range)
-- are produced by the existing SkuOptions:IterateOptionsArgs from an AceConfig
-- `options.args` table (the "settings" kind delegates to it), NOT reimplemented
-- here, so their exact navigation semantics are preserved by reuse.
--
-- Kinds:
--   { kind = "list",     label=, build=fn(entry) }                       -- dynamic, rebuilt each visit
--   { kind = "submenu",  label=, build=fn(entry) | children=specList }   -- dynamic container
--   { kind = "action",   label=, run=fn(self,value,name,parentName) }    -- leaf; Enter runs run()
--   { kind = "settings", label=, args=<options.args>, db=<subtable>, module=<name> } -- IterateOptionsArgs container; module enables schema-managed get/set (W2-MC1)
--
-- Any spec may ALSO carry these optional fields, copied verbatim onto the node so
-- a converted hand-built entry keeps its EXACT property set (faithful, mechanical
-- conversion): sorting, dynamic, isSelect, isMultiselect, noStepUpAfterSelect,
-- macrotext, secureMacro, tooltip (-> textFull), and the handlers onAction
-- (-> OnAction), onEnter, onLeave, getCurrentValue, onUpdate, onKey.
local function specLabel(aSpec)
	local lbl = aSpec.label
	if type(lbl) == "function" then
		local ok, r = pcall(lbl)
		if ok and r ~= nil then return r end
		return ""
	end
	return lbl ~= nil and lbl or ""
end

local PASSTHROUGH_FLAGS = {
	"sorting", "dynamic", "isSelect", "isMultiselect",
	"actionInPlace",  -- [v43.0] act-here-stay-here (templates.lua)
	"noStepUpAfterSelect", "macrotext", "secureMacro",
	"id",  -- stable nav anchor (W6-B #14): a Build spec may carry an id
}
local PASSTHROUGH_HANDLERS = {
	onAction = "OnAction", onEnter = "OnEnter", onLeave = "OnLeave",
	getCurrentValue = "GetCurrentValue", onUpdate = "OnUpdate", onKey = "OnKey",
}

-- Copy the optional flags/handlers a spec carries onto the template node, so a
-- converted entry reproduces its hand-built property set exactly.
local function applyCommon(aEntry, aSpec)
	for _, f in ipairs(PASSTHROUGH_FLAGS) do
		if aSpec[f] ~= nil then aEntry[f] = aSpec[f] end
	end
	if aSpec.tooltip ~= nil then aEntry.textFull = aSpec.tooltip end
	for specKey, nodeKey in pairs(PASSTHROUGH_HANDLERS) do
		if aSpec[specKey] ~= nil then aEntry[nodeKey] = aSpec[specKey] end
	end
end

function SkuMenu:BuildNode(aParent, aSpec)
	if type(aSpec) ~= "table" then return nil end
	local kind = aSpec.kind
	local tEntry = SkuOptions:InjectMenuItems(aParent, {specLabel(aSpec)}, SkuGenericMenuItem)
	applyCommon(tEntry, aSpec)

	if kind == "list" then
		-- Dynamic container: children rebuilt on each visit. `build` is assigned
		-- DIRECTLY as BuildChildren (not wrapped) so it receives the exact same
		-- args the renderer passes (`self:BuildChildren(self)` -> (entry, entry)).
		-- This matters for a build that is a colon-method reference
		-- (e.g. SkuCore.AuctionHouse.AuctionHouseMenuBuilder, which needs aParentEntry as its
		-- second positional) — a one-arg wrapper would pass it nil.
		tEntry.dynamic = true
		if aSpec.build then
			tEntry.BuildChildren = aSpec.build
		end

	elseif kind == "submenu" then
		-- Container: either a custom build closure/method (assigned directly, as
		-- above) or a nested spec list. When neither is given it is a static
		-- container the caller fills itself.
		if aSpec.build then
			tEntry.dynamic = true
			tEntry.BuildChildren = aSpec.build
		elseif aSpec.children then
			tEntry.dynamic = true
			local children = aSpec.children
			tEntry.BuildChildren = function(self)
				SkuMenu:Build(self, children)
			end
		end

	elseif kind == "action" then
		-- Leaf: Enter runs run(); flags like macrotext/secureMacro come via
		-- applyCommon. An explicit onAction (set above) wins over run.
		if aSpec.run and aSpec.onAction == nil then
			local run = aSpec.run
			tEntry.OnAction = function(self, aValue, aName, aParentMenuName)
				run(self, aValue, aName, aParentMenuName)
			end
		end

	elseif kind == "settings" then
		-- Named container populated immediately from an AceConfig args table via
		-- the existing IterateOptionsArgs (toggle/select/range/execute children).
		if aSpec.sorting == nil then tEntry.sorting = true end
		if aSpec.args then
			SkuOptions:IterateOptionsArgs(aSpec.args, tEntry, aSpec.db, aSpec.module)
		end

	else
		if dprint then dprint("SkuMenu:BuildNode: unknown kind", tostring(kind)) end
		return nil
	end

	return tEntry
end

-- Compile a flat list of specs under aParent, in order (prev/next wired centrally
-- by InjectMenuItems, exactly as a hand-built sequence would be).
function SkuMenu:Build(aParent, aSpecs)
	if type(aSpecs) ~= "table" then return self end
	for i = 1, #aSpecs do
		self:BuildNode(aParent, aSpecs[i])
	end
	return self
end

---------------------------------------------------------------------------------------------------------------------------------------
-- Root contributions. Centralised here DELIBERATELY (W6-B #10, resolving the old
-- "trivial follow-up" TODO as won't-do): keeping every root RegisterModule call
-- in one reviewable file beside SetRootLayout means "what is on the root and in
-- what order" stays greppable in a single place. Scattering these into the owning
-- modules buys nothing (builders/labels already resolve their globals lazily at
-- open time) and would only make the root layout harder to find. The one
-- exception is a dynamically-toggled module that self-registers from its owner
-- (SkuCore/ModuleManager registers "Features" — it is not appended to the root
-- layout, only referenced by id). Labels resolve at open time too, matching the
-- original (which read L[...] inside the open handler).
local function L() return Sku.L end

SkuMenu:RegisterModule("SkuNav",   { label = function() return L()["SkuNavMenuEntry"]   end, build = function(entry) SkuNav:MenuBuilder(entry)   end })
-- W7: top-level entry is the target action menu directly (label "Ziel Menue"),
-- not a "Mob" wrapper. SkuMob's settings live under Einstellungen -> Sonstiges.
SkuMenu:RegisterModule("SkuMob",   { label = function() return L()["Target menu"]       end, build = function(entry) SkuMob:MenuBuilder(entry)   end })
-- pcall per registration: a failure building any one of these (SkuChat has
-- had init trouble on some clients this session) must not stop the rest from
-- registering -- that would take the whole menu (bags included) down with it.
pcall(SkuMenu.RegisterModule, SkuMenu, "SkuChat",  { label = function() return L()["SkuChatMenuEntry"]  end, build = function(entry) SkuChat:MenuBuilder(entry)  end })
pcall(SkuMenu.RegisterModule, SkuMenu, "SkuQuest", { label = function() return L()["SkuQuestMenuEntry"] end, build = function(entry) SkuQuest:MenuBuilder(entry) end })
-- W7: "Core" grab-bag is gone; SkuCore:MenuBuilder now builds the aggregated
-- "Einstellungen" (Settings) tree.
pcall(SkuMenu.RegisterModule, SkuMenu, "Einstellungen", { label = function() return Sku.deEn("Einstellungen", "Settings", "Réglages") end, build = function(entry) SkuCore:MenuBuilder(entry)  end })
pcall(SkuMenu.RegisterModule, SkuMenu, "SkuAuras", { label = function() return L()["SkuAurasMenuEntry"] end, build = function(entry) SkuAuras:MenuBuilder(entry) end })

-- Game Options: Blizzard's built-in game options (modern Settings system, else
-- only reachable via the Escape menu) made accessible through Sku's menu. Logic
-- in SkuCore/gameOptions.lua. Title is locale-computed at open time, as before.
SkuMenu:RegisterModule("GameOptions", {
	label = function() return Sku.deEn("Spieloptionen", "Game Options", "Options du jeu") end,
	build = function(entry)
		if SkuCore and SkuCore.GameOptions and SkuCore.GameOptions.GameOptionsMenuBuilder then
			SkuCore.GameOptions:GameOptionsMenuBuilder(entry)
		end
	end,
})

-- Root shortcut to Blizzard's audio assistance (screen reader + combat announcer), so the
-- health/resource call-outs and the duplicate ones can be switched without digging through
-- Einstellungen -> Spieleinstellungen. Builder in SkuCore/gameOptions.lua.
SkuMenu:RegisterModule("BlizzardAudio", {
	label = function() return Sku.deEn("Blizzard Ansagen", "Blizzard call-outs", "Annonces Blizzard") end,
	build = function(entry)
		if SkuCore and SkuCore.GameOptions and SkuCore.GameOptions.AudioAssistMenuBuilder then
			SkuCore.GameOptions:AudioAssistMenuBuilder(entry)
		end
	end,
})

-- W7: Monitor and Macros promoted from children of "Core" to top-level entries.
-- Builders resolve lazily and are called via a DOT (not colon) so their implicit
-- `self` is the menu entry (the convention their bodies rely on), matching the old
-- `build = SkuCore.X.YMenuBuilder` specs.
SkuMenu:RegisterModule("Monitor", {
	label = function() return L()["Monitor"] end,
	build = function(entry) if SkuCore.Aq and SkuCore.Aq.MonitorMenuBuilder then SkuCore.Aq.MonitorMenuBuilder(entry) end end,
})
SkuMenu:RegisterModule("Macros", {
	label = function() return L()["Macros"] end,
	build = function(entry) if SkuCore.Macro and SkuCore.Macro.MacroMenuBuilder then SkuCore.Macro.MacroMenuBuilder(entry) end end,
})

-- W7: addons container — collects addon integrations (Atlas Loot, Damage Meter, ...)
-- that previously lived directly under "Core". Subtree built by SkuCore:AddonsMenuBuilder.
SkuMenu:RegisterModule("Addons", {
	label = function() return "Addons" end,
	build = function(entry) if SkuCore and SkuCore.AddonsMenuBuilder then SkuCore:AddonsMenuBuilder(entry) end end,
})

-- [42.13] The "Werkzeuge" (Tools) root container is gone: it only ever held
-- "Dial Targeting" and "Soft Targeting", and both now live directly in the
-- Schnellmenue (Barrierefreiheit) root entry, built in SkuZOptions/Core.lua.
-- Same builders / same db + keyPrefix -> saved values unchanged.

-- W7: the Escape game menu (Spielmenue) — the live game-menu actions, with Optionen
-- routed to Einstellungen and Makros to the Sku macro menu. SkuCore:GameMenuShowHandler
-- navigates here when the Blizzard GameMenuFrame is invoked.
SkuMenu:RegisterModule("GameMenu", {
	label = function() return Sku.deEn("Spielmenü", "Game menu", "Menu du jeu") end,
	build = function(entry) if SkuCore and SkuCore.GameOptions and SkuCore.GameOptions.GameMenuBuilder then SkuCore.GameOptions:GameMenuBuilder(entry) end end,
})

-- W7 root layout: target/nav/chat/monitor/macros/auren/addons up front (the intended
-- order), with the still-transitional "Core" + "GameOptions" kept reachable until they
-- fold into the Einstellungen tree in the next batch. SkuQuest dropped from the root —
-- quests are now reached by opening the quest-log window (a Local contributor).
-- "Features", Barrierefreiheit and the old "Optionen" are still appended after this
-- (ModuleManager / SkuZOptions Core.lua); "Lokal" is spliced in last when a window is open.
SkuMenu:SetRootLayout({
	"SkuMob",      -- target
	"SkuNav",      -- nav
	"SkuChat",     -- chat
	"Monitor",
	"Macros",
	"SkuAuras",    -- auren
	"Addons",
	"Einstellungen",
})
-- "GameMenu" (Spielmenü) is intentionally NOT in the layout: like "Local", it is
-- spliced in only for an Escape session by SkuCore:UpdateGameMenuRootEntry.
-- GameOptions is NOT at root — it lives under Einstellungen -> Spieleinstellungen,
-- and the Escape (GameMenuFrame) hook now navigates there (SkuCore:GameMenuShowHandler).
